id: I9B8C4E13
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:38:46+00:00'
last_modified: '2022-06-08T04:39:52.842845+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17212
  title: རྟ་ནག་ཐུབ་བསྟན་རྣམ་རྒྱལ་གྱི་རྟེན་གདན་རབས་དང་བཅས་པའི་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ་ངོ་མཚར་དད་པའི་སྒོ་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E487:
      image_group_id: I1KG17633
      title: ''
      total_pages: 48
      order: 1
      base_file: E487.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
