id: P004453
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17212
  title: རྟ་ནག་ཐུབ་བསྟན་རྣམ་རྒྱལ་གྱི་རྟེན་གདན་རབས་དང་བཅས་པའི་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ་ངོ་མཚར་དད་པའི་སྒོ་འབྱེད།
  author: ''
  volumes:
    d6d81f6c3dd44c41a1dc9e69135b3216:
      image_group_id: I1KG17633
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
