id: opecha:P004453
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17212
  title: རྟ་ནག་ཐུབ་བསྟན་རྣམ་རྒྱལ་གྱི་རྟེན་གདན་རབས་དང་བཅས་པའི་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ་ངོ་མཚར་དད་པའི་སྒོ་འབྱེད།
  volume: ''
  author: ''
